name: Ruby

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '2.7.6'
          - '3.0.4'
          - '3.1.2'

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Bundle
        run: bundle install
      - name: Appraisal install
        run: bundle exec appraisal install

      - name: Lint
        run: bundle exec rubocop
      - name: Build and test
        run: bundle exec appraisal rspec
